package com.lekerand.model;
// Generated 18 janv. 2016 18:33:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * CycleScolaire generated by hbm2java
 */
@Entity
@Table(name = "cycle_scolaire", catalog = "dauphin_bd")
public class CycleScolaire implements java.io.Serializable {

	private int idSyclescolaire;
	private String libSyclscolaire;
	private Set<Classe> classes = new HashSet<Classe>(0);

	public CycleScolaire() {
	}

	public CycleScolaire(int idSyclescolaire) {
		this.idSyclescolaire = idSyclescolaire;
	}

	public CycleScolaire(int idSyclescolaire, String libSyclscolaire, Set<Classe> classes) {
		this.idSyclescolaire = idSyclescolaire;
		this.libSyclscolaire = libSyclscolaire;
		this.classes = classes;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_SYCLESCOLAIRE", unique = true, nullable = false)
	public int getIdSyclescolaire() {
		return this.idSyclescolaire;
	}

	public void setIdSyclescolaire(int idSyclescolaire) {
		this.idSyclescolaire = idSyclescolaire;
	}

	@Column(name = "LIB_SYCLSCOLAIRE", length = 15)
	public String getLibSyclscolaire() {
		return this.libSyclscolaire;
	}

	public void setLibSyclscolaire(String libSyclscolaire) {
		this.libSyclscolaire = libSyclscolaire;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cycleScolaire")
	public Set<Classe> getClasses() {
		return this.classes;
	}

	public void setClasses(Set<Classe> classes) {
		this.classes = classes;
	}

}
