package com.lekerand.model;
// Generated 18 janv. 2016 18:33:35 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Eleve generated by hbm2java
 */
@Entity
@Table(name = "eleve", catalog = "dauphin_bd")
public class Eleve implements java.io.Serializable {

	private String idEleve;
	private Sexe sexe;
	private String nomEleve;
	private String prenomsEleve;
	private Date datenaisEleve;
	private String lieunaisEleve;
	private String pereEleve;
	private String mereEleve;
	private String photoEleve;
	private Set<Versement> versements = new HashSet<Versement>(0);
	private Set<Inscription> inscriptions = new HashSet<Inscription>(0);

	public Eleve() {
	}

	public Eleve(String idEleve, Sexe sexe) {
		this.idEleve = idEleve;
		this.sexe = sexe;
	}

	public Eleve(String idEleve, Sexe sexe, String nomEleve, String prenomsEleve, Date datenaisEleve,
			String lieunaisEleve, String pereEleve, String mereEleve, String photoEleve, Set<Versement> versements,
			Set<Inscription> inscriptions) {
		this.idEleve = idEleve;
		this.sexe = sexe;
		this.nomEleve = nomEleve;
		this.prenomsEleve = prenomsEleve;
		this.datenaisEleve = datenaisEleve;
		this.lieunaisEleve = lieunaisEleve;
		this.pereEleve = pereEleve;
		this.mereEleve = mereEleve;
		this.photoEleve = photoEleve;
		this.versements = versements;
		this.inscriptions = inscriptions;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_ELEVE", unique = true, nullable = false, length = 20)
	public String getIdEleve() {
		return this.idEleve;
	}

	public void setIdEleve(String idEleve) {
		this.idEleve = idEleve;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_SEXE", nullable = false)
	public Sexe getSexe() {
		return this.sexe;
	}

	public void setSexe(Sexe sexe) {
		this.sexe = sexe;
	}

	@Column(name = "NOM_ELEVE", length = 20)
	public String getNomEleve() {
		return this.nomEleve;
	}

	public void setNomEleve(String nomEleve) {
		this.nomEleve = nomEleve;
	}

	@Column(name = "PRENOMS_ELEVE", length = 50)
	public String getPrenomsEleve() {
		return this.prenomsEleve;
	}

	public void setPrenomsEleve(String prenomsEleve) {
		this.prenomsEleve = prenomsEleve;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATENAIS_ELEVE", length = 10)
	public Date getDatenaisEleve() {
		return this.datenaisEleve;
	}

	public void setDatenaisEleve(Date datenaisEleve) {
		this.datenaisEleve = datenaisEleve;
	}

	@Column(name = "LIEUNAIS_ELEVE", length = 25)
	public String getLieunaisEleve() {
		return this.lieunaisEleve;
	}

	public void setLieunaisEleve(String lieunaisEleve) {
		this.lieunaisEleve = lieunaisEleve;
	}

	@Column(name = "PERE_ELEVE", length = 50)
	public String getPereEleve() {
		return this.pereEleve;
	}

	public void setPereEleve(String pereEleve) {
		this.pereEleve = pereEleve;
	}

	@Column(name = "MERE_ELEVE", length = 50)
	public String getMereEleve() {
		return this.mereEleve;
	}

	public void setMereEleve(String mereEleve) {
		this.mereEleve = mereEleve;
	}

	@Column(name = "PHOTO_ELEVE")
	public String getPhotoEleve() {
		return this.photoEleve;
	}

	public void setPhotoEleve(String photoEleve) {
		this.photoEleve = photoEleve;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleve")
	public Set<Versement> getVersements() {
		return this.versements;
	}

	public void setVersements(Set<Versement> versements) {
		this.versements = versements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleve")
	public Set<Inscription> getInscriptions() {
		return this.inscriptions;
	}

	public void setInscriptions(Set<Inscription> inscriptions) {
		this.inscriptions = inscriptions;
	}

}
