package com.lekerand.model;
// Generated 18 janv. 2016 18:33:35 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Etablissement generated by hbm2java
 */
@Entity
@Table(name = "etablissement", catalog = "dauphin_bd")
public class Etablissement implements java.io.Serializable {

	private int idEtablissement;
	private String nomEtablis;
	private String signeEtabl;
	private String logoEtablis;

	public Etablissement() {
	}

	public Etablissement(int idEtablissement) {
		this.idEtablissement = idEtablissement;
	}

	public Etablissement(int idEtablissement, String nomEtablis, String signeEtabl, String logoEtablis) {
		this.idEtablissement = idEtablissement;
		this.nomEtablis = nomEtablis;
		this.signeEtabl = signeEtabl;
		this.logoEtablis = logoEtablis;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_ETABLISSEMENT", unique = true, nullable = false)
	public int getIdEtablissement() {
		return this.idEtablissement;
	}

	public void setIdEtablissement(int idEtablissement) {
		this.idEtablissement = idEtablissement;
	}

	@Column(name = "NOM_ETABLIS", length = 50)
	public String getNomEtablis() {
		return this.nomEtablis;
	}

	public void setNomEtablis(String nomEtablis) {
		this.nomEtablis = nomEtablis;
	}

	@Column(name = "SIGNE_ETABL", length = 10)
	public String getSigneEtabl() {
		return this.signeEtabl;
	}

	public void setSigneEtabl(String signeEtabl) {
		this.signeEtabl = signeEtabl;
	}

	@Column(name = "LOGO_ETABLIS")
	public String getLogoEtablis() {
		return this.logoEtablis;
	}

	public void setLogoEtablis(String logoEtablis) {
		this.logoEtablis = logoEtablis;
	}

}
