package com.lekerand.model;
// Generated 14 janv. 2016 15:58:37 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FraisClasseId generated by hbm2java
 */
@Embeddable
public class FraisClasseId implements java.io.Serializable {

	private int idClasse;
	private int codeFrais;

	public FraisClasseId() {
	}

	public FraisClasseId(int idClasse, int codeFrais) {
		this.idClasse = idClasse;
		this.codeFrais = codeFrais;
	}

	@Column(name = "ID_CLASSE", nullable = false)
	public int getIdClasse() {
		return this.idClasse;
	}

	public void setIdClasse(int idClasse) {
		this.idClasse = idClasse;
	}

	@Column(name = "CODE_FRAIS", nullable = false)
	public int getCodeFrais() {
		return this.codeFrais;
	}

	public void setCodeFrais(int codeFrais) {
		this.codeFrais = codeFrais;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FraisClasseId))
			return false;
		FraisClasseId castOther = (FraisClasseId) other;

		return (this.getIdClasse() == castOther.getIdClasse()) && (this.getCodeFrais() == castOther.getCodeFrais());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdClasse();
		result = 37 * result + this.getCodeFrais();
		return result;
	}

}
