package com.lekerand.model;
// Generated 18 janv. 2016 18:33:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mode generated by hbm2java
 */
@Entity
@Table(name = "mode", catalog = "dauphin_bd")
public class Mode implements java.io.Serializable {

	private int codeMode;
	private String libMode;
	private Set<Versement> versements = new HashSet<Versement>(0);

	public Mode() {
	}

	public Mode(int codeMode) {
		this.codeMode = codeMode;
	}

	public Mode(int codeMode, String libMode, Set<Versement> versements) {
		this.codeMode = codeMode;
		this.libMode = libMode;
		this.versements = versements;
	}

	@Id

	@Column(name = "CODE_MODE", unique = true, nullable = false)
	public int getCodeMode() {
		return this.codeMode;
	}

	public void setCodeMode(int codeMode) {
		this.codeMode = codeMode;
	}

	@Column(name = "LIB_MODE", length = 20)
	public String getLibMode() {
		return this.libMode;
	}

	public void setLibMode(String libMode) {
		this.libMode = libMode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mode")
	public Set<Versement> getVersements() {
		return this.versements;
	}

	public void setVersements(Set<Versement> versements) {
		this.versements = versements;
	}

}
