package com.lekerand.model;
// Generated 14 janv. 2016 15:58:37 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Niveau generated by hbm2java
 */
@Entity
@Table(name = "niveau", catalog = "dauphin_bd")
public class Niveau implements java.io.Serializable {

	private int idNiveau;
	private String libNiveau;
	private Set<Classe> classes = new HashSet<Classe>(0);

	public Niveau() {
	}

	public Niveau(int idNiveau) {
		this.idNiveau = idNiveau;
	}

	public Niveau(int idNiveau, String libNiveau, Set<Classe> classes) {
		this.idNiveau = idNiveau;
		this.libNiveau = libNiveau;
		this.classes = classes;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_NIVEAU", unique = true, nullable = false)
	public int getIdNiveau() {
		return this.idNiveau;
	}

	public void setIdNiveau(int idNiveau) {
		this.idNiveau = idNiveau;
	}

	@Column(name = "LIB_NIVEAU", length = 25)
	public String getLibNiveau() {
		return this.libNiveau;
	}

	public void setLibNiveau(String libNiveau) {
		this.libNiveau = libNiveau;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "niveau")
	public Set<Classe> getClasses() {
		return this.classes;
	}

	public void setClasses(Set<Classe> classes) {
		this.classes = classes;
	}

}
