package com.lekerand.model;
// Generated 14 janv. 2016 15:58:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personnel generated by hbm2java
 */
@Entity
@Table(name = "personnel", catalog = "dauphin_bd")
public class Personnel implements java.io.Serializable {

	private int idPersonnel;
	private Fonction fonction;
	private String nomPersonnel;
	private String prenomsPersonnel;
	private Date dateNaisPersonnel;
	private String lieunaisPersonnel;
	private Set<Enseigner> enseigners = new HashSet<Enseigner>(0);

	public Personnel() {
	}

	public Personnel(int idPersonnel, Fonction fonction) {
		this.idPersonnel = idPersonnel;
		this.fonction = fonction;
	}

	public Personnel(int idPersonnel, Fonction fonction, String nomPersonnel, String prenomsPersonnel,
			Date dateNaisPersonnel, String lieunaisPersonnel, Set<Enseigner> enseigners) {
		this.idPersonnel = idPersonnel;
		this.fonction = fonction;
		this.nomPersonnel = nomPersonnel;
		this.prenomsPersonnel = prenomsPersonnel;
		this.dateNaisPersonnel = dateNaisPersonnel;
		this.lieunaisPersonnel = lieunaisPersonnel;
		this.enseigners = enseigners;
	}

	@Id

	@Column(name = "ID_PERSONNEL", unique = true, nullable = false)
	public int getIdPersonnel() {
		return this.idPersonnel;
	}

	public void setIdPersonnel(int idPersonnel) {
		this.idPersonnel = idPersonnel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_FONCTION", nullable = false)
	public Fonction getFonction() {
		return this.fonction;
	}

	public void setFonction(Fonction fonction) {
		this.fonction = fonction;
	}

	@Column(name = "NOM_PERSONNEL", length = 15)
	public String getNomPersonnel() {
		return this.nomPersonnel;
	}

	public void setNomPersonnel(String nomPersonnel) {
		this.nomPersonnel = nomPersonnel;
	}

	@Column(name = "PRENOMS_PERSONNEL", length = 50)
	public String getPrenomsPersonnel() {
		return this.prenomsPersonnel;
	}

	public void setPrenomsPersonnel(String prenomsPersonnel) {
		this.prenomsPersonnel = prenomsPersonnel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAIS_PERSONNEL", length = 10)
	public Date getDateNaisPersonnel() {
		return this.dateNaisPersonnel;
	}

	public void setDateNaisPersonnel(Date dateNaisPersonnel) {
		this.dateNaisPersonnel = dateNaisPersonnel;
	}

	@Column(name = "LIEUNAIS_PERSONNEL", length = 30)
	public String getLieunaisPersonnel() {
		return this.lieunaisPersonnel;
	}

	public void setLieunaisPersonnel(String lieunaisPersonnel) {
		this.lieunaisPersonnel = lieunaisPersonnel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnel")
	public Set<Enseigner> getEnseigners() {
		return this.enseigners;
	}

	public void setEnseigners(Set<Enseigner> enseigners) {
		this.enseigners = enseigners;
	}

}
