package com.lekerand.model;
// Generated 18 janv. 2016 18:33:35 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Versement generated by hbm2java
 */
@Entity
@Table(name = "versement", catalog = "dauphin_bd")
public class Versement implements java.io.Serializable {

	private int codeVers;
	private AnneeScolaire anneeScolaire;
	private Eleve eleve;
	private Mode mode;
	private Long montantVers;
	private Date dateVers;

	public Versement() {
	}

	public Versement(int codeVers, AnneeScolaire anneeScolaire, Eleve eleve, Mode mode) {
		this.codeVers = codeVers;
		this.anneeScolaire = anneeScolaire;
		this.eleve = eleve;
		this.mode = mode;
	}

	public Versement(int codeVers, AnneeScolaire anneeScolaire, Eleve eleve, Mode mode, Long montantVers,
			Date dateVers) {
		this.codeVers = codeVers;
		this.anneeScolaire = anneeScolaire;
		this.eleve = eleve;
		this.mode = mode;
		this.montantVers = montantVers;
		this.dateVers = dateVers;
	}

	@Id

	@Column(name = "CODE_VERS", unique = true, nullable = false)
	public int getCodeVers() {
		return this.codeVers;
	}

	public void setCodeVers(int codeVers) {
		this.codeVers = codeVers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ANNEE_SCOLAIRE", nullable = false)
	public AnneeScolaire getAnneeScolaire() {
		return this.anneeScolaire;
	}

	public void setAnneeScolaire(AnneeScolaire anneeScolaire) {
		this.anneeScolaire = anneeScolaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ELEVE", nullable = false)
	public Eleve getEleve() {
		return this.eleve;
	}

	public void setEleve(Eleve eleve) {
		this.eleve = eleve;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_MODE", nullable = false)
	public Mode getMode() {
		return this.mode;
	}

	public void setMode(Mode mode) {
		this.mode = mode;
	}

	@Column(name = "MONTANT_VERS", precision = 10, scale = 0)
	public Long getMontantVers() {
		return this.montantVers;
	}

	public void setMontantVers(Long montantVers) {
		this.montantVers = montantVers;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_VERS", length = 10)
	public Date getDateVers() {
		return this.dateVers;
	}

	public void setDateVers(Date dateVers) {
		this.dateVers = dateVers;
	}

}
